### PR TITLE
feat: Add code completion and annotator support for steps.*.{conclusion,outcome}

### PR DESCRIPTION
**Pull request by siketyan**
### Types of changes
  - [ ] Bug fix (non-breaking change which fixes an issue)
  - [x] New feature (non-breaking change which adds functionality)
  - [ ] Breaking change (fix or feature that would cause existing functionality to change)

Code completion and annotation is incomplete for items under steps.* other than `outputs`.

This pull request adds code completion and annotator support for `steps.*.conclusion` and `steps.*.outcome`. These properties are documented at https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context.

image

Try opening this simple workflow:

```yaml
name: checks

on:
  pull_request: ~

jobs:
  checks:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        id: checkout

      - run: echo "${{ steps.checkout.outcome }}"
```

### CODE REVIEW

**Comment by YunaBraska** [comment]
Wow amazing, 🤩 thank you. I will have a look on it tomorrow.

**Comment by YunaBraska** [comment]
The Version [3.1.0](https://plugins.jetbrains.com/plugin/21396-github-workflow/versions/stable/417681) is on the way 🎉.

Just one general thing, you only tested the happy path ^^ When you program, please also test the error cases. But no worries, I have added the step validation to the new case. Was a nice collaboration! Thank you!
Greetings from Germany to Japan 🥇

**Comment by siketyan** [comment]
Sorry for missing test cases, thank you for quick review & merge!

**Comment by YunaBraska** [comment]
No worries, no sorry 😉 was just a friendly hint

**Pull request merged**
